/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the auditoria service. Represents a row in the &quot;GENERO_AUDITORIA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ability.genero.server.model.impl.auditoriaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ability.genero.server.model.impl.auditoriaImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see auditoria
 * @see com.ability.genero.server.model.impl.auditoriaImpl
 * @see com.ability.genero.server.model.impl.auditoriaModelImpl
 * @generated
 */
public interface auditoriaModel extends BaseModel<auditoria> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a auditoria model instance should use the {@link auditoria} interface instead.
	 */

	/**
	 * Returns the primary key of this auditoria.
	 *
	 * @return the primary key of this auditoria
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this auditoria.
	 *
	 * @param primaryKey the primary key of this auditoria
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this auditoria.
	 *
	 * @return the ID of this auditoria
	 */
	public long getId();

	/**
	 * Sets the ID of this auditoria.
	 *
	 * @param id the ID of this auditoria
	 */
	public void setId(long id);

	/**
	 * Returns the fecha of this auditoria.
	 *
	 * @return the fecha of this auditoria
	 */
	public Date getFecha();

	/**
	 * Sets the fecha of this auditoria.
	 *
	 * @param fecha the fecha of this auditoria
	 */
	public void setFecha(Date fecha);

	/**
	 * Returns the evento of this auditoria.
	 *
	 * @return the evento of this auditoria
	 */
	@AutoEscape
	public String getEvento();

	/**
	 * Sets the evento of this auditoria.
	 *
	 * @param evento the evento of this auditoria
	 */
	public void setEvento(String evento);

	/**
	 * Returns the tabla of this auditoria.
	 *
	 * @return the tabla of this auditoria
	 */
	@AutoEscape
	public String getTabla();

	/**
	 * Sets the tabla of this auditoria.
	 *
	 * @param tabla the tabla of this auditoria
	 */
	public void setTabla(String tabla);

	/**
	 * Returns the logs of this auditoria.
	 *
	 * @return the logs of this auditoria
	 */
	@AutoEscape
	public String getLogs();

	/**
	 * Sets the logs of this auditoria.
	 *
	 * @param logs the logs of this auditoria
	 */
	public void setLogs(String logs);

	/**
	 * Returns the id user of this auditoria.
	 *
	 * @return the id user of this auditoria
	 */
	public long getIdUser();

	/**
	 * Sets the id user of this auditoria.
	 *
	 * @param idUser the id user of this auditoria
	 */
	public void setIdUser(long idUser);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(auditoria auditoria);

	public int hashCode();

	public CacheModel<auditoria> toCacheModel();

	public auditoria toEscapedModel();

	public String toString();

	public String toXmlString();
}