/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ciudades service. Represents a row in the &quot;VC_CIUDADES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ability.genero.server.model.impl.ciudadesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ability.genero.server.model.impl.ciudadesImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see ciudades
 * @see com.ability.genero.server.model.impl.ciudadesImpl
 * @see com.ability.genero.server.model.impl.ciudadesModelImpl
 * @generated
 */
public interface ciudadesModel extends BaseModel<ciudades> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ciudades model instance should use the {@link ciudades} interface instead.
	 */

	/**
	 * Returns the primary key of this ciudades.
	 *
	 * @return the primary key of this ciudades
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this ciudades.
	 *
	 * @param primaryKey the primary key of this ciudades
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the codigo of this ciudades.
	 *
	 * @return the codigo of this ciudades
	 */
	@AutoEscape
	public String getCodigo();

	/**
	 * Sets the codigo of this ciudades.
	 *
	 * @param codigo the codigo of this ciudades
	 */
	public void setCodigo(String codigo);

	/**
	 * Returns the nombre of this ciudades.
	 *
	 * @return the nombre of this ciudades
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this ciudades.
	 *
	 * @param nombre the nombre of this ciudades
	 */
	public void setNombre(String nombre);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ciudades ciudades);

	public int hashCode();

	public CacheModel<ciudades> toCacheModel();

	public ciudades toEscapedModel();

	public String toString();

	public String toXmlString();
}