/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the claseProceso service. Represents a row in the &quot;GENERO_CLASE_PROCESO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ability.genero.server.model.impl.claseProcesoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ability.genero.server.model.impl.claseProcesoImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see claseProceso
 * @see com.ability.genero.server.model.impl.claseProcesoImpl
 * @see com.ability.genero.server.model.impl.claseProcesoModelImpl
 * @generated
 */
public interface claseProcesoModel extends BaseModel<claseProceso> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a clase proceso model instance should use the {@link claseProceso} interface instead.
	 */

	/**
	 * Returns the primary key of this clase proceso.
	 *
	 * @return the primary key of this clase proceso
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this clase proceso.
	 *
	 * @param primaryKey the primary key of this clase proceso
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this clase proceso.
	 *
	 * @return the ID of this clase proceso
	 */
	public int getId();

	/**
	 * Sets the ID of this clase proceso.
	 *
	 * @param id the ID of this clase proceso
	 */
	public void setId(int id);

	/**
	 * Returns the clase proceso of this clase proceso.
	 *
	 * @return the clase proceso of this clase proceso
	 */
	@AutoEscape
	public String getClaseProceso();

	/**
	 * Sets the clase proceso of this clase proceso.
	 *
	 * @param claseProceso the clase proceso of this clase proceso
	 */
	public void setClaseProceso(String claseProceso);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(claseProceso claseProceso);

	public int hashCode();

	public CacheModel<claseProceso> toCacheModel();

	public claseProceso toEscapedModel();

	public String toString();

	public String toXmlString();
}