/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the despacho service. Represents a row in the &quot;VC_DESPACHO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ability.genero.server.model.impl.despachoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ability.genero.server.model.impl.despachoImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see despacho
 * @see com.ability.genero.server.model.impl.despachoImpl
 * @see com.ability.genero.server.model.impl.despachoModelImpl
 * @generated
 */
public interface despachoModel extends BaseModel<despacho> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a despacho model instance should use the {@link despacho} interface instead.
	 */

	/**
	 * Returns the primary key of this despacho.
	 *
	 * @return the primary key of this despacho
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this despacho.
	 *
	 * @param primaryKey the primary key of this despacho
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this despacho.
	 *
	 * @return the ID of this despacho
	 */
	public int getId();

	/**
	 * Sets the ID of this despacho.
	 *
	 * @param id the ID of this despacho
	 */
	public void setId(int id);

	/**
	 * Returns the jurisdiccion of this despacho.
	 *
	 * @return the jurisdiccion of this despacho
	 */
	@AutoEscape
	public String getJurisdiccion();

	/**
	 * Sets the jurisdiccion of this despacho.
	 *
	 * @param jurisdiccion the jurisdiccion of this despacho
	 */
	public void setJurisdiccion(String jurisdiccion);

	/**
	 * Returns the distrito of this despacho.
	 *
	 * @return the distrito of this despacho
	 */
	@AutoEscape
	public String getDistrito();

	/**
	 * Sets the distrito of this despacho.
	 *
	 * @param distrito the distrito of this despacho
	 */
	public void setDistrito(String distrito);

	/**
	 * Returns the circuito of this despacho.
	 *
	 * @return the circuito of this despacho
	 */
	@AutoEscape
	public String getCircuito();

	/**
	 * Sets the circuito of this despacho.
	 *
	 * @param circuito the circuito of this despacho
	 */
	public void setCircuito(String circuito);

	/**
	 * Returns the municipio of this despacho.
	 *
	 * @return the municipio of this despacho
	 */
	@AutoEscape
	public String getMunicipio();

	/**
	 * Sets the municipio of this despacho.
	 *
	 * @param municipio the municipio of this despacho
	 */
	public void setMunicipio(String municipio);

	/**
	 * Returns the codigo despacho of this despacho.
	 *
	 * @return the codigo despacho of this despacho
	 */
	@AutoEscape
	public String getCodigoDespacho();

	/**
	 * Sets the codigo despacho of this despacho.
	 *
	 * @param codigoDespacho the codigo despacho of this despacho
	 */
	public void setCodigoDespacho(String codigoDespacho);

	/**
	 * Returns the nombre of this despacho.
	 *
	 * @return the nombre of this despacho
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this despacho.
	 *
	 * @param nombre the nombre of this despacho
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the jues despacho of this despacho.
	 *
	 * @return the jues despacho of this despacho
	 */
	@AutoEscape
	public String getJuesDespacho();

	/**
	 * Sets the jues despacho of this despacho.
	 *
	 * @param juesDespacho the jues despacho of this despacho
	 */
	public void setJuesDespacho(String juesDespacho);

	/**
	 * Returns the correo of this despacho.
	 *
	 * @return the correo of this despacho
	 */
	@AutoEscape
	public String getCorreo();

	/**
	 * Sets the correo of this despacho.
	 *
	 * @param Correo the correo of this despacho
	 */
	public void setCorreo(String Correo);

	/**
	 * Returns the direccion of this despacho.
	 *
	 * @return the direccion of this despacho
	 */
	@AutoEscape
	public String getDireccion();

	/**
	 * Sets the direccion of this despacho.
	 *
	 * @param direccion the direccion of this despacho
	 */
	public void setDireccion(String direccion);

	/**
	 * Returns the telefono of this despacho.
	 *
	 * @return the telefono of this despacho
	 */
	@AutoEscape
	public String getTelefono();

	/**
	 * Sets the telefono of this despacho.
	 *
	 * @param telefono the telefono of this despacho
	 */
	public void setTelefono(String telefono);

	/**
	 * Returns the horario of this despacho.
	 *
	 * @return the horario of this despacho
	 */
	@AutoEscape
	public String getHorario();

	/**
	 * Sets the horario of this despacho.
	 *
	 * @param horario the horario of this despacho
	 */
	public void setHorario(String horario);

	/**
	 * Returns the area of this despacho.
	 *
	 * @return the area of this despacho
	 */
	@AutoEscape
	public String getArea();

	/**
	 * Sets the area of this despacho.
	 *
	 * @param area the area of this despacho
	 */
	public void setArea(String area);

	/**
	 * Returns the departamento of this despacho.
	 *
	 * @return the departamento of this despacho
	 */
	@AutoEscape
	public String getDepartamento();

	/**
	 * Sets the departamento of this despacho.
	 *
	 * @param departamento the departamento of this despacho
	 */
	public void setDepartamento(String departamento);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(despacho despacho);

	public int hashCode();

	public CacheModel<despacho> toCacheModel();

	public despacho toEscapedModel();

	public String toString();

	public String toXmlString();
}