/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the distritoG service. Represents a row in the &quot;GENERO_DISTRITOS_MASCARAS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ability.genero.server.model.impl.distritoGModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ability.genero.server.model.impl.distritoGImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see distritoG
 * @see com.ability.genero.server.model.impl.distritoGImpl
 * @see com.ability.genero.server.model.impl.distritoGModelImpl
 * @generated
 */
public interface distritoGModel extends BaseModel<distritoG> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a distrito g model instance should use the {@link distritoG} interface instead.
	 */

	/**
	 * Returns the primary key of this distrito g.
	 *
	 * @return the primary key of this distrito g
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this distrito g.
	 *
	 * @param primaryKey the primary key of this distrito g
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this distrito g.
	 *
	 * @return the ID of this distrito g
	 */
	public int getId();

	/**
	 * Sets the ID of this distrito g.
	 *
	 * @param id the ID of this distrito g
	 */
	public void setId(int id);

	/**
	 * Returns the nombre of this distrito g.
	 *
	 * @return the nombre of this distrito g
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this distrito g.
	 *
	 * @param nombre the nombre of this distrito g
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the nombre_mascara of this distrito g.
	 *
	 * @return the nombre_mascara of this distrito g
	 */
	@AutoEscape
	public String getNombre_mascara();

	/**
	 * Sets the nombre_mascara of this distrito g.
	 *
	 * @param nombre_mascara the nombre_mascara of this distrito g
	 */
	public void setNombre_mascara(String nombre_mascara);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(distritoG distritoG);

	public int hashCode();

	public CacheModel<distritoG> toCacheModel();

	public distritoG toEscapedModel();

	public String toString();

	public String toXmlString();
}