/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the encuestaEnfoDife service. Represents a row in the &quot;GENERO_ENCUESTA_ENFOQUEDIFERENCIAL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ability.genero.server.model.impl.encuestaEnfoDifeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ability.genero.server.model.impl.encuestaEnfoDifeImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see encuestaEnfoDife
 * @see com.ability.genero.server.model.impl.encuestaEnfoDifeImpl
 * @see com.ability.genero.server.model.impl.encuestaEnfoDifeModelImpl
 * @generated
 */
public interface encuestaEnfoDifeModel extends BaseModel<encuestaEnfoDife> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a encuesta enfo dife model instance should use the {@link encuestaEnfoDife} interface instead.
	 */

	/**
	 * Returns the primary key of this encuesta enfo dife.
	 *
	 * @return the primary key of this encuesta enfo dife
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this encuesta enfo dife.
	 *
	 * @param primaryKey the primary key of this encuesta enfo dife
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this encuesta enfo dife.
	 *
	 * @return the ID of this encuesta enfo dife
	 */
	public int getId();

	/**
	 * Sets the ID of this encuesta enfo dife.
	 *
	 * @param id the ID of this encuesta enfo dife
	 */
	public void setId(int id);

	/**
	 * Returns the pregunta of this encuesta enfo dife.
	 *
	 * @return the pregunta of this encuesta enfo dife
	 */
	@AutoEscape
	public String getPregunta();

	/**
	 * Sets the pregunta of this encuesta enfo dife.
	 *
	 * @param pregunta the pregunta of this encuesta enfo dife
	 */
	public void setPregunta(String pregunta);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(encuestaEnfoDife encuestaEnfoDife);

	public int hashCode();

	public CacheModel<encuestaEnfoDife> toCacheModel();

	public encuestaEnfoDife toEscapedModel();

	public String toString();

	public String toXmlString();
}