/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the generoUsuarioComite service. Represents a row in the &quot;GENERO_USUARIOS_COMITE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ability.genero.server.model.impl.generoUsuarioComiteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ability.genero.server.model.impl.generoUsuarioComiteImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see generoUsuarioComite
 * @see com.ability.genero.server.model.impl.generoUsuarioComiteImpl
 * @see com.ability.genero.server.model.impl.generoUsuarioComiteModelImpl
 * @generated
 */
public interface generoUsuarioComiteModel extends BaseModel<generoUsuarioComite> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a genero usuario comite model instance should use the {@link generoUsuarioComite} interface instead.
	 */

	/**
	 * Returns the primary key of this genero usuario comite.
	 *
	 * @return the primary key of this genero usuario comite
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this genero usuario comite.
	 *
	 * @param primaryKey the primary key of this genero usuario comite
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this genero usuario comite.
	 *
	 * @return the ID of this genero usuario comite
	 */
	public int getId();

	/**
	 * Sets the ID of this genero usuario comite.
	 *
	 * @param id the ID of this genero usuario comite
	 */
	public void setId(int id);

	/**
	 * Returns the distrito of this genero usuario comite.
	 *
	 * @return the distrito of this genero usuario comite
	 */
	@AutoEscape
	public String getDistrito();

	/**
	 * Sets the distrito of this genero usuario comite.
	 *
	 * @param Distrito the distrito of this genero usuario comite
	 */
	public void setDistrito(String Distrito);

	/**
	 * Returns the user ID of this genero usuario comite.
	 *
	 * @return the user ID of this genero usuario comite
	 */
	@AutoEscape
	public String getUserId();

	/**
	 * Sets the user ID of this genero usuario comite.
	 *
	 * @param userId the user ID of this genero usuario comite
	 */
	public void setUserId(String userId);

	/**
	 * Returns the fecha_creacion of this genero usuario comite.
	 *
	 * @return the fecha_creacion of this genero usuario comite
	 */
	public Date getFecha_creacion();

	/**
	 * Sets the fecha_creacion of this genero usuario comite.
	 *
	 * @param fecha_creacion the fecha_creacion of this genero usuario comite
	 */
	public void setFecha_creacion(Date fecha_creacion);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(generoUsuarioComite generoUsuarioComite);

	public int hashCode();

	public CacheModel<generoUsuarioComite> toCacheModel();

	public generoUsuarioComite toEscapedModel();

	public String toString();

	public String toXmlString();
}