/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the juresprudenciaNacional service. Represents a row in the &quot;GENERO_JURISPRUDENCIA_NACIONAL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ability.genero.server.model.impl.juresprudenciaNacionalModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ability.genero.server.model.impl.juresprudenciaNacionalImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see juresprudenciaNacional
 * @see com.ability.genero.server.model.impl.juresprudenciaNacionalImpl
 * @see com.ability.genero.server.model.impl.juresprudenciaNacionalModelImpl
 * @generated
 */
public interface juresprudenciaNacionalModel extends BaseModel<juresprudenciaNacional> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a juresprudencia nacional model instance should use the {@link juresprudenciaNacional} interface instead.
	 */

	/**
	 * Returns the primary key of this juresprudencia nacional.
	 *
	 * @return the primary key of this juresprudencia nacional
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this juresprudencia nacional.
	 *
	 * @param primaryKey the primary key of this juresprudencia nacional
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this juresprudencia nacional.
	 *
	 * @return the ID of this juresprudencia nacional
	 */
	public int getId();

	/**
	 * Sets the ID of this juresprudencia nacional.
	 *
	 * @param id the ID of this juresprudencia nacional
	 */
	public void setId(int id);

	/**
	 * Returns the referencias of this juresprudencia nacional.
	 *
	 * @return the referencias of this juresprudencia nacional
	 */
	@AutoEscape
	public String getReferencias();

	/**
	 * Sets the referencias of this juresprudencia nacional.
	 *
	 * @param referencias the referencias of this juresprudencia nacional
	 */
	public void setReferencias(String referencias);

	/**
	 * Returns the corporacion of this juresprudencia nacional.
	 *
	 * @return the corporacion of this juresprudencia nacional
	 */
	@AutoEscape
	public String getCorporacion();

	/**
	 * Sets the corporacion of this juresprudencia nacional.
	 *
	 * @param corporacion the corporacion of this juresprudencia nacional
	 */
	public void setCorporacion(String corporacion);

	/**
	 * Returns the url of this juresprudencia nacional.
	 *
	 * @return the url of this juresprudencia nacional
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this juresprudencia nacional.
	 *
	 * @param url the url of this juresprudencia nacional
	 */
	public void setUrl(String url);

	/**
	 * Returns the ambito of this juresprudencia nacional.
	 *
	 * @return the ambito of this juresprudencia nacional
	 */
	@AutoEscape
	public String getAmbito();

	/**
	 * Sets the ambito of this juresprudencia nacional.
	 *
	 * @param ambito the ambito of this juresprudencia nacional
	 */
	public void setAmbito(String ambito);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(juresprudenciaNacional juresprudenciaNacional);

	public int hashCode();

	public CacheModel<juresprudenciaNacional> toCacheModel();

	public juresprudenciaNacional toEscapedModel();

	public String toString();

	public String toXmlString();
}