/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model.impl;

import com.ability.genero.server.model.casoLV;
import com.ability.genero.server.model.casoLVModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the casoLV service. Represents a row in the &quot;GENERO_LV_CASO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ability.genero.server.model.casoLVModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link casoLVImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see casoLVImpl
 * @see com.ability.genero.server.model.casoLV
 * @see com.ability.genero.server.model.casoLVModel
 * @generated
 */
public class casoLVModelImpl extends BaseModelImpl<casoLV>
	implements casoLVModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a caso l v model instance should use the {@link com.ability.genero.server.model.casoLV} interface instead.
	 */
	public static final String TABLE_NAME = "GENERO_LV_CASO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "DESPACHO", Types.VARCHAR },
			{ "RADICACION", Types.VARCHAR },
			{ "DEMANDANTE", Types.VARCHAR },
			{ "DEMANDADO", Types.VARCHAR },
			{ "CLASE_PROCESO", Types.VARCHAR },
			{ "TIPO_DECISION", Types.VARCHAR },
			{ "PONENTE", Types.VARCHAR },
			{ "FECHA", Types.TIMESTAMP },
			{ "CATEGORIA", Types.VARCHAR },
			{ "SUBCATEGORIA", Types.VARCHAR },
			{ "RESPUESTAS1", Types.VARCHAR },
			{ "RESPUESTAS2", Types.VARCHAR },
			{ "ANHIO", Types.VARCHAR },
			{ "GENERODEMANDANTE", Types.VARCHAR },
			{ "GENERODEMANDADO", Types.VARCHAR },
			{ "ARCHIVO", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table GENERO_LV_CASO (ID INTEGER not null primary key,DESPACHO VARCHAR(75) null,RADICACION VARCHAR(75) null,DEMANDANTE VARCHAR(75) null,DEMANDADO VARCHAR(75) null,CLASE_PROCESO VARCHAR(75) null,TIPO_DECISION VARCHAR(75) null,PONENTE VARCHAR(75) null,FECHA DATE null,CATEGORIA VARCHAR(75) null,SUBCATEGORIA VARCHAR(75) null,RESPUESTAS1 VARCHAR(75) null,RESPUESTAS2 VARCHAR(75) null,ANHIO VARCHAR(75) null,GENERODEMANDANTE VARCHAR(75) null,GENERODEMANDADO VARCHAR(75) null,ARCHIVO VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table GENERO_LV_CASO";
	public static final String ORDER_BY_JPQL = " ORDER BY casoLV.fecha DESC";
	public static final String ORDER_BY_SQL = " ORDER BY GENERO_LV_CASO.FECHA DESC";
	public static final String DATA_SOURCE = "base_datos_csjDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ability.genero.server.model.casoLV"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ability.genero.server.model.casoLV"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ability.genero.server.model.casoLV"),
			true);
	public static long ANHIO_COLUMN_BITMASK = 1L;
	public static long DESPACHO_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ability.genero.server.model.casoLV"));

	public casoLVModelImpl() {
	}

	public int getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return casoLV.class;
	}

	public String getModelClassName() {
		return casoLV.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("despacho", getDespacho());
		attributes.put("radicacion", getRadicacion());
		attributes.put("demandante", getDemandante());
		attributes.put("demandado", getDemandado());
		attributes.put("claseProceso", getClaseProceso());
		attributes.put("tipoDecision", getTipoDecision());
		attributes.put("ponente", getPonente());
		attributes.put("fecha", getFecha());
		attributes.put("categoria", getCategoria());
		attributes.put("subCategoria", getSubCategoria());
		attributes.put("respuestas1", getRespuestas1());
		attributes.put("respuestas2", getRespuestas2());
		attributes.put("anhio", getAnhio());
		attributes.put("generoDemandante", getGeneroDemandante());
		attributes.put("generoDemandado", getGeneroDemandado());
		attributes.put("archivo", getArchivo());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String despacho = (String)attributes.get("despacho");

		if (despacho != null) {
			setDespacho(despacho);
		}

		String radicacion = (String)attributes.get("radicacion");

		if (radicacion != null) {
			setRadicacion(radicacion);
		}

		String demandante = (String)attributes.get("demandante");

		if (demandante != null) {
			setDemandante(demandante);
		}

		String demandado = (String)attributes.get("demandado");

		if (demandado != null) {
			setDemandado(demandado);
		}

		String claseProceso = (String)attributes.get("claseProceso");

		if (claseProceso != null) {
			setClaseProceso(claseProceso);
		}

		String tipoDecision = (String)attributes.get("tipoDecision");

		if (tipoDecision != null) {
			setTipoDecision(tipoDecision);
		}

		String ponente = (String)attributes.get("ponente");

		if (ponente != null) {
			setPonente(ponente);
		}

		Date fecha = (Date)attributes.get("fecha");

		if (fecha != null) {
			setFecha(fecha);
		}

		String categoria = (String)attributes.get("categoria");

		if (categoria != null) {
			setCategoria(categoria);
		}

		String subCategoria = (String)attributes.get("subCategoria");

		if (subCategoria != null) {
			setSubCategoria(subCategoria);
		}

		String respuestas1 = (String)attributes.get("respuestas1");

		if (respuestas1 != null) {
			setRespuestas1(respuestas1);
		}

		String respuestas2 = (String)attributes.get("respuestas2");

		if (respuestas2 != null) {
			setRespuestas2(respuestas2);
		}

		String anhio = (String)attributes.get("anhio");

		if (anhio != null) {
			setAnhio(anhio);
		}

		String generoDemandante = (String)attributes.get("generoDemandante");

		if (generoDemandante != null) {
			setGeneroDemandante(generoDemandante);
		}

		String generoDemandado = (String)attributes.get("generoDemandado");

		if (generoDemandado != null) {
			setGeneroDemandado(generoDemandado);
		}

		String archivo = (String)attributes.get("archivo");

		if (archivo != null) {
			setArchivo(archivo);
		}
	}

	public int getId() {
		return _id;
	}

	public void setId(int id) {
		_id = id;
	}

	public String getDespacho() {
		if (_despacho == null) {
			return StringPool.BLANK;
		}
		else {
			return _despacho;
		}
	}

	public void setDespacho(String despacho) {
		_columnBitmask |= DESPACHO_COLUMN_BITMASK;

		if (_originalDespacho == null) {
			_originalDespacho = _despacho;
		}

		_despacho = despacho;
	}

	public String getOriginalDespacho() {
		return GetterUtil.getString(_originalDespacho);
	}

	public String getRadicacion() {
		if (_radicacion == null) {
			return StringPool.BLANK;
		}
		else {
			return _radicacion;
		}
	}

	public void setRadicacion(String radicacion) {
		_radicacion = radicacion;
	}

	public String getDemandante() {
		if (_demandante == null) {
			return StringPool.BLANK;
		}
		else {
			return _demandante;
		}
	}

	public void setDemandante(String demandante) {
		_demandante = demandante;
	}

	public String getDemandado() {
		if (_demandado == null) {
			return StringPool.BLANK;
		}
		else {
			return _demandado;
		}
	}

	public void setDemandado(String demandado) {
		_demandado = demandado;
	}

	public String getClaseProceso() {
		if (_claseProceso == null) {
			return StringPool.BLANK;
		}
		else {
			return _claseProceso;
		}
	}

	public void setClaseProceso(String claseProceso) {
		_claseProceso = claseProceso;
	}

	public String getTipoDecision() {
		if (_tipoDecision == null) {
			return StringPool.BLANK;
		}
		else {
			return _tipoDecision;
		}
	}

	public void setTipoDecision(String tipoDecision) {
		_tipoDecision = tipoDecision;
	}

	public String getPonente() {
		if (_ponente == null) {
			return StringPool.BLANK;
		}
		else {
			return _ponente;
		}
	}

	public void setPonente(String ponente) {
		_ponente = ponente;
	}

	public Date getFecha() {
		return _fecha;
	}

	public void setFecha(Date fecha) {
		_columnBitmask = -1L;

		_fecha = fecha;
	}

	public String getCategoria() {
		if (_categoria == null) {
			return StringPool.BLANK;
		}
		else {
			return _categoria;
		}
	}

	public void setCategoria(String categoria) {
		_categoria = categoria;
	}

	public String getSubCategoria() {
		if (_subCategoria == null) {
			return StringPool.BLANK;
		}
		else {
			return _subCategoria;
		}
	}

	public void setSubCategoria(String subCategoria) {
		_subCategoria = subCategoria;
	}

	public String getRespuestas1() {
		if (_respuestas1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _respuestas1;
		}
	}

	public void setRespuestas1(String respuestas1) {
		_respuestas1 = respuestas1;
	}

	public String getRespuestas2() {
		if (_respuestas2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _respuestas2;
		}
	}

	public void setRespuestas2(String respuestas2) {
		_respuestas2 = respuestas2;
	}

	public String getAnhio() {
		if (_anhio == null) {
			return StringPool.BLANK;
		}
		else {
			return _anhio;
		}
	}

	public void setAnhio(String anhio) {
		_columnBitmask |= ANHIO_COLUMN_BITMASK;

		if (_originalAnhio == null) {
			_originalAnhio = _anhio;
		}

		_anhio = anhio;
	}

	public String getOriginalAnhio() {
		return GetterUtil.getString(_originalAnhio);
	}

	public String getGeneroDemandante() {
		if (_generoDemandante == null) {
			return StringPool.BLANK;
		}
		else {
			return _generoDemandante;
		}
	}

	public void setGeneroDemandante(String generoDemandante) {
		_generoDemandante = generoDemandante;
	}

	public String getGeneroDemandado() {
		if (_generoDemandado == null) {
			return StringPool.BLANK;
		}
		else {
			return _generoDemandado;
		}
	}

	public void setGeneroDemandado(String generoDemandado) {
		_generoDemandado = generoDemandado;
	}

	public String getArchivo() {
		if (_archivo == null) {
			return StringPool.BLANK;
		}
		else {
			return _archivo;
		}
	}

	public void setArchivo(String archivo) {
		_archivo = archivo;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public casoLV toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (casoLV)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		casoLVImpl casoLVImpl = new casoLVImpl();

		casoLVImpl.setId(getId());
		casoLVImpl.setDespacho(getDespacho());
		casoLVImpl.setRadicacion(getRadicacion());
		casoLVImpl.setDemandante(getDemandante());
		casoLVImpl.setDemandado(getDemandado());
		casoLVImpl.setClaseProceso(getClaseProceso());
		casoLVImpl.setTipoDecision(getTipoDecision());
		casoLVImpl.setPonente(getPonente());
		casoLVImpl.setFecha(getFecha());
		casoLVImpl.setCategoria(getCategoria());
		casoLVImpl.setSubCategoria(getSubCategoria());
		casoLVImpl.setRespuestas1(getRespuestas1());
		casoLVImpl.setRespuestas2(getRespuestas2());
		casoLVImpl.setAnhio(getAnhio());
		casoLVImpl.setGeneroDemandante(getGeneroDemandante());
		casoLVImpl.setGeneroDemandado(getGeneroDemandado());
		casoLVImpl.setArchivo(getArchivo());

		casoLVImpl.resetOriginalValues();

		return casoLVImpl;
	}

	public int compareTo(casoLV casoLV) {
		int value = 0;

		value = DateUtil.compareTo(getFecha(), casoLV.getFecha());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		casoLV casoLV = null;

		try {
			casoLV = (casoLV)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = casoLV.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		casoLVModelImpl casoLVModelImpl = this;

		casoLVModelImpl._originalDespacho = casoLVModelImpl._despacho;

		casoLVModelImpl._originalAnhio = casoLVModelImpl._anhio;

		casoLVModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<casoLV> toCacheModel() {
		casoLVCacheModel casoLVCacheModel = new casoLVCacheModel();

		casoLVCacheModel.id = getId();

		casoLVCacheModel.despacho = getDespacho();

		String despacho = casoLVCacheModel.despacho;

		if ((despacho != null) && (despacho.length() == 0)) {
			casoLVCacheModel.despacho = null;
		}

		casoLVCacheModel.radicacion = getRadicacion();

		String radicacion = casoLVCacheModel.radicacion;

		if ((radicacion != null) && (radicacion.length() == 0)) {
			casoLVCacheModel.radicacion = null;
		}

		casoLVCacheModel.demandante = getDemandante();

		String demandante = casoLVCacheModel.demandante;

		if ((demandante != null) && (demandante.length() == 0)) {
			casoLVCacheModel.demandante = null;
		}

		casoLVCacheModel.demandado = getDemandado();

		String demandado = casoLVCacheModel.demandado;

		if ((demandado != null) && (demandado.length() == 0)) {
			casoLVCacheModel.demandado = null;
		}

		casoLVCacheModel.claseProceso = getClaseProceso();

		String claseProceso = casoLVCacheModel.claseProceso;

		if ((claseProceso != null) && (claseProceso.length() == 0)) {
			casoLVCacheModel.claseProceso = null;
		}

		casoLVCacheModel.tipoDecision = getTipoDecision();

		String tipoDecision = casoLVCacheModel.tipoDecision;

		if ((tipoDecision != null) && (tipoDecision.length() == 0)) {
			casoLVCacheModel.tipoDecision = null;
		}

		casoLVCacheModel.ponente = getPonente();

		String ponente = casoLVCacheModel.ponente;

		if ((ponente != null) && (ponente.length() == 0)) {
			casoLVCacheModel.ponente = null;
		}

		Date fecha = getFecha();

		if (fecha != null) {
			casoLVCacheModel.fecha = fecha.getTime();
		}
		else {
			casoLVCacheModel.fecha = Long.MIN_VALUE;
		}

		casoLVCacheModel.categoria = getCategoria();

		String categoria = casoLVCacheModel.categoria;

		if ((categoria != null) && (categoria.length() == 0)) {
			casoLVCacheModel.categoria = null;
		}

		casoLVCacheModel.subCategoria = getSubCategoria();

		String subCategoria = casoLVCacheModel.subCategoria;

		if ((subCategoria != null) && (subCategoria.length() == 0)) {
			casoLVCacheModel.subCategoria = null;
		}

		casoLVCacheModel.respuestas1 = getRespuestas1();

		String respuestas1 = casoLVCacheModel.respuestas1;

		if ((respuestas1 != null) && (respuestas1.length() == 0)) {
			casoLVCacheModel.respuestas1 = null;
		}

		casoLVCacheModel.respuestas2 = getRespuestas2();

		String respuestas2 = casoLVCacheModel.respuestas2;

		if ((respuestas2 != null) && (respuestas2.length() == 0)) {
			casoLVCacheModel.respuestas2 = null;
		}

		casoLVCacheModel.anhio = getAnhio();

		String anhio = casoLVCacheModel.anhio;

		if ((anhio != null) && (anhio.length() == 0)) {
			casoLVCacheModel.anhio = null;
		}

		casoLVCacheModel.generoDemandante = getGeneroDemandante();

		String generoDemandante = casoLVCacheModel.generoDemandante;

		if ((generoDemandante != null) && (generoDemandante.length() == 0)) {
			casoLVCacheModel.generoDemandante = null;
		}

		casoLVCacheModel.generoDemandado = getGeneroDemandado();

		String generoDemandado = casoLVCacheModel.generoDemandado;

		if ((generoDemandado != null) && (generoDemandado.length() == 0)) {
			casoLVCacheModel.generoDemandado = null;
		}

		casoLVCacheModel.archivo = getArchivo();

		String archivo = casoLVCacheModel.archivo;

		if ((archivo != null) && (archivo.length() == 0)) {
			casoLVCacheModel.archivo = null;
		}

		return casoLVCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(35);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", despacho=");
		sb.append(getDespacho());
		sb.append(", radicacion=");
		sb.append(getRadicacion());
		sb.append(", demandante=");
		sb.append(getDemandante());
		sb.append(", demandado=");
		sb.append(getDemandado());
		sb.append(", claseProceso=");
		sb.append(getClaseProceso());
		sb.append(", tipoDecision=");
		sb.append(getTipoDecision());
		sb.append(", ponente=");
		sb.append(getPonente());
		sb.append(", fecha=");
		sb.append(getFecha());
		sb.append(", categoria=");
		sb.append(getCategoria());
		sb.append(", subCategoria=");
		sb.append(getSubCategoria());
		sb.append(", respuestas1=");
		sb.append(getRespuestas1());
		sb.append(", respuestas2=");
		sb.append(getRespuestas2());
		sb.append(", anhio=");
		sb.append(getAnhio());
		sb.append(", generoDemandante=");
		sb.append(getGeneroDemandante());
		sb.append(", generoDemandado=");
		sb.append(getGeneroDemandado());
		sb.append(", archivo=");
		sb.append(getArchivo());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(55);

		sb.append("<model><model-name>");
		sb.append("com.ability.genero.server.model.casoLV");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>despacho</column-name><column-value><![CDATA[");
		sb.append(getDespacho());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>radicacion</column-name><column-value><![CDATA[");
		sb.append(getRadicacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>demandante</column-name><column-value><![CDATA[");
		sb.append(getDemandante());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>demandado</column-name><column-value><![CDATA[");
		sb.append(getDemandado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>claseProceso</column-name><column-value><![CDATA[");
		sb.append(getClaseProceso());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipoDecision</column-name><column-value><![CDATA[");
		sb.append(getTipoDecision());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ponente</column-name><column-value><![CDATA[");
		sb.append(getPonente());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fecha</column-name><column-value><![CDATA[");
		sb.append(getFecha());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>categoria</column-name><column-value><![CDATA[");
		sb.append(getCategoria());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subCategoria</column-name><column-value><![CDATA[");
		sb.append(getSubCategoria());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>respuestas1</column-name><column-value><![CDATA[");
		sb.append(getRespuestas1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>respuestas2</column-name><column-value><![CDATA[");
		sb.append(getRespuestas2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anhio</column-name><column-value><![CDATA[");
		sb.append(getAnhio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>generoDemandante</column-name><column-value><![CDATA[");
		sb.append(getGeneroDemandante());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>generoDemandado</column-name><column-value><![CDATA[");
		sb.append(getGeneroDemandado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>archivo</column-name><column-value><![CDATA[");
		sb.append(getArchivo());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = casoLV.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			casoLV.class
		};
	private int _id;
	private String _despacho;
	private String _originalDespacho;
	private String _radicacion;
	private String _demandante;
	private String _demandado;
	private String _claseProceso;
	private String _tipoDecision;
	private String _ponente;
	private Date _fecha;
	private String _categoria;
	private String _subCategoria;
	private String _respuestas1;
	private String _respuestas2;
	private String _anhio;
	private String _originalAnhio;
	private String _generoDemandante;
	private String _generoDemandado;
	private String _archivo;
	private long _columnBitmask;
	private casoLV _escapedModelProxy;
}