/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model.impl;

import com.ability.genero.server.model.claseProceso;
import com.ability.genero.server.model.claseProcesoModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the claseProceso service. Represents a row in the &quot;GENERO_CLASE_PROCESO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ability.genero.server.model.claseProcesoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link claseProcesoImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see claseProcesoImpl
 * @see com.ability.genero.server.model.claseProceso
 * @see com.ability.genero.server.model.claseProcesoModel
 * @generated
 */
public class claseProcesoModelImpl extends BaseModelImpl<claseProceso>
	implements claseProcesoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a clase proceso model instance should use the {@link com.ability.genero.server.model.claseProceso} interface instead.
	 */
	public static final String TABLE_NAME = "GENERO_CLASE_PROCESO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "CLASE_PROCESO", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table GENERO_CLASE_PROCESO (ID INTEGER not null primary key,CLASE_PROCESO VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table GENERO_CLASE_PROCESO";
	public static final String DATA_SOURCE = "base_datos_csjDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ability.genero.server.model.claseProceso"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ability.genero.server.model.claseProceso"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ability.genero.server.model.claseProceso"));

	public claseProcesoModelImpl() {
	}

	public int getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return claseProceso.class;
	}

	public String getModelClassName() {
		return claseProceso.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("claseProceso", getClaseProceso());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String claseProceso = (String)attributes.get("claseProceso");

		if (claseProceso != null) {
			setClaseProceso(claseProceso);
		}
	}

	public int getId() {
		return _id;
	}

	public void setId(int id) {
		_id = id;
	}

	public String getClaseProceso() {
		if (_claseProceso == null) {
			return StringPool.BLANK;
		}
		else {
			return _claseProceso;
		}
	}

	public void setClaseProceso(String claseProceso) {
		_claseProceso = claseProceso;
	}

	@Override
	public claseProceso toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (claseProceso)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		claseProcesoImpl claseProcesoImpl = new claseProcesoImpl();

		claseProcesoImpl.setId(getId());
		claseProcesoImpl.setClaseProceso(getClaseProceso());

		claseProcesoImpl.resetOriginalValues();

		return claseProcesoImpl;
	}

	public int compareTo(claseProceso claseProceso) {
		int primaryKey = claseProceso.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		claseProceso claseProceso = null;

		try {
			claseProceso = (claseProceso)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = claseProceso.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<claseProceso> toCacheModel() {
		claseProcesoCacheModel claseProcesoCacheModel = new claseProcesoCacheModel();

		claseProcesoCacheModel.id = getId();

		claseProcesoCacheModel.claseProceso = getClaseProceso();

		String claseProceso = claseProcesoCacheModel.claseProceso;

		if ((claseProceso != null) && (claseProceso.length() == 0)) {
			claseProcesoCacheModel.claseProceso = null;
		}

		return claseProcesoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", claseProceso=");
		sb.append(getClaseProceso());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.ability.genero.server.model.claseProceso");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>claseProceso</column-name><column-value><![CDATA[");
		sb.append(getClaseProceso());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = claseProceso.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			claseProceso.class
		};
	private int _id;
	private String _claseProceso;
	private claseProceso _escapedModelProxy;
}