/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model.impl;

import com.ability.genero.server.model.distritoG;
import com.ability.genero.server.service.distritoGLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the distritoG service. Represents a row in the &quot;GENERO_DISTRITOS_MASCARAS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link distritoGImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see distritoGImpl
 * @see com.ability.genero.server.model.distritoG
 * @generated
 */
public abstract class distritoGBaseImpl extends distritoGModelImpl
	implements distritoG {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a distrito g model instance should use the {@link distritoG} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			distritoGLocalServiceUtil.adddistritoG(this);
		}
		else {
			distritoGLocalServiceUtil.updatedistritoG(this);
		}
	}
}