/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model.impl;

import com.ability.genero.server.model.encuestaEnfoDife;
import com.ability.genero.server.model.encuestaEnfoDifeModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the encuestaEnfoDife service. Represents a row in the &quot;GENERO_ENCUESTA_ENFOQUEDIFERENCIAL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ability.genero.server.model.encuestaEnfoDifeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link encuestaEnfoDifeImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see encuestaEnfoDifeImpl
 * @see com.ability.genero.server.model.encuestaEnfoDife
 * @see com.ability.genero.server.model.encuestaEnfoDifeModel
 * @generated
 */
public class encuestaEnfoDifeModelImpl extends BaseModelImpl<encuestaEnfoDife>
	implements encuestaEnfoDifeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a encuesta enfo dife model instance should use the {@link com.ability.genero.server.model.encuestaEnfoDife} interface instead.
	 */
	public static final String TABLE_NAME = "GENERO_ENCUESTA_ENFOQUEDIFERENCIAL";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "PREGUNTA", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table GENERO_ENCUESTA_ENFOQUEDIFERENCIAL (ID INTEGER not null primary key,PREGUNTA VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table GENERO_ENCUESTA_ENFOQUEDIFERENCIAL";
	public static final String ORDER_BY_JPQL = " ORDER BY encuestaEnfoDife.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GENERO_ENCUESTA_ENFOQUEDIFERENCIAL.ID ASC";
	public static final String DATA_SOURCE = "base_datos_csjDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ability.genero.server.model.encuestaEnfoDife"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ability.genero.server.model.encuestaEnfoDife"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ability.genero.server.model.encuestaEnfoDife"));

	public encuestaEnfoDifeModelImpl() {
	}

	public int getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return encuestaEnfoDife.class;
	}

	public String getModelClassName() {
		return encuestaEnfoDife.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("pregunta", getPregunta());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String pregunta = (String)attributes.get("pregunta");

		if (pregunta != null) {
			setPregunta(pregunta);
		}
	}

	public int getId() {
		return _id;
	}

	public void setId(int id) {
		_id = id;
	}

	public String getPregunta() {
		if (_pregunta == null) {
			return StringPool.BLANK;
		}
		else {
			return _pregunta;
		}
	}

	public void setPregunta(String pregunta) {
		_pregunta = pregunta;
	}

	@Override
	public encuestaEnfoDife toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (encuestaEnfoDife)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		encuestaEnfoDifeImpl encuestaEnfoDifeImpl = new encuestaEnfoDifeImpl();

		encuestaEnfoDifeImpl.setId(getId());
		encuestaEnfoDifeImpl.setPregunta(getPregunta());

		encuestaEnfoDifeImpl.resetOriginalValues();

		return encuestaEnfoDifeImpl;
	}

	public int compareTo(encuestaEnfoDife encuestaEnfoDife) {
		int value = 0;

		if (getId() < encuestaEnfoDife.getId()) {
			value = -1;
		}
		else if (getId() > encuestaEnfoDife.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		encuestaEnfoDife encuestaEnfoDife = null;

		try {
			encuestaEnfoDife = (encuestaEnfoDife)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = encuestaEnfoDife.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<encuestaEnfoDife> toCacheModel() {
		encuestaEnfoDifeCacheModel encuestaEnfoDifeCacheModel = new encuestaEnfoDifeCacheModel();

		encuestaEnfoDifeCacheModel.id = getId();

		encuestaEnfoDifeCacheModel.pregunta = getPregunta();

		String pregunta = encuestaEnfoDifeCacheModel.pregunta;

		if ((pregunta != null) && (pregunta.length() == 0)) {
			encuestaEnfoDifeCacheModel.pregunta = null;
		}

		return encuestaEnfoDifeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", pregunta=");
		sb.append(getPregunta());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.ability.genero.server.model.encuestaEnfoDife");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pregunta</column-name><column-value><![CDATA[");
		sb.append(getPregunta());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = encuestaEnfoDife.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			encuestaEnfoDife.class
		};
	private int _id;
	private String _pregunta;
	private encuestaEnfoDife _escapedModelProxy;
}