/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model.impl;

import com.ability.genero.server.model.generoUsuarioComite;
import com.ability.genero.server.model.generoUsuarioComiteModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the generoUsuarioComite service. Represents a row in the &quot;GENERO_USUARIOS_COMITE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ability.genero.server.model.generoUsuarioComiteModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link generoUsuarioComiteImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see generoUsuarioComiteImpl
 * @see com.ability.genero.server.model.generoUsuarioComite
 * @see com.ability.genero.server.model.generoUsuarioComiteModel
 * @generated
 */
public class generoUsuarioComiteModelImpl extends BaseModelImpl<generoUsuarioComite>
	implements generoUsuarioComiteModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a genero usuario comite model instance should use the {@link com.ability.genero.server.model.generoUsuarioComite} interface instead.
	 */
	public static final String TABLE_NAME = "GENERO_USUARIOS_COMITE";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "DISTRITO", Types.VARCHAR },
			{ "USER_ID", Types.VARCHAR },
			{ "FECHA_CREACION", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table GENERO_USUARIOS_COMITE (ID INTEGER not null primary key,DISTRITO VARCHAR(75) null,USER_ID VARCHAR(75) null,FECHA_CREACION DATE null)";
	public static final String TABLE_SQL_DROP = "drop table GENERO_USUARIOS_COMITE";
	public static final String DATA_SOURCE = "base_datos_csjDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ability.genero.server.model.generoUsuarioComite"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ability.genero.server.model.generoUsuarioComite"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ability.genero.server.model.generoUsuarioComite"),
			true);
	public static long USERID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ability.genero.server.model.generoUsuarioComite"));

	public generoUsuarioComiteModelImpl() {
	}

	public int getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return generoUsuarioComite.class;
	}

	public String getModelClassName() {
		return generoUsuarioComite.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("Distrito", getDistrito());
		attributes.put("userId", getUserId());
		attributes.put("fecha_creacion", getFecha_creacion());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String Distrito = (String)attributes.get("Distrito");

		if (Distrito != null) {
			setDistrito(Distrito);
		}

		String userId = (String)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date fecha_creacion = (Date)attributes.get("fecha_creacion");

		if (fecha_creacion != null) {
			setFecha_creacion(fecha_creacion);
		}
	}

	public int getId() {
		return _id;
	}

	public void setId(int id) {
		_id = id;
	}

	public String getDistrito() {
		if (_Distrito == null) {
			return StringPool.BLANK;
		}
		else {
			return _Distrito;
		}
	}

	public void setDistrito(String Distrito) {
		_Distrito = Distrito;
	}

	public String getUserId() {
		if (_userId == null) {
			return StringPool.BLANK;
		}
		else {
			return _userId;
		}
	}

	public void setUserId(String userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (_originalUserId == null) {
			_originalUserId = _userId;
		}

		_userId = userId;
	}

	public String getOriginalUserId() {
		return GetterUtil.getString(_originalUserId);
	}

	public Date getFecha_creacion() {
		return _fecha_creacion;
	}

	public void setFecha_creacion(Date fecha_creacion) {
		_fecha_creacion = fecha_creacion;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public generoUsuarioComite toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (generoUsuarioComite)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		generoUsuarioComiteImpl generoUsuarioComiteImpl = new generoUsuarioComiteImpl();

		generoUsuarioComiteImpl.setId(getId());
		generoUsuarioComiteImpl.setDistrito(getDistrito());
		generoUsuarioComiteImpl.setUserId(getUserId());
		generoUsuarioComiteImpl.setFecha_creacion(getFecha_creacion());

		generoUsuarioComiteImpl.resetOriginalValues();

		return generoUsuarioComiteImpl;
	}

	public int compareTo(generoUsuarioComite generoUsuarioComite) {
		int primaryKey = generoUsuarioComite.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		generoUsuarioComite generoUsuarioComite = null;

		try {
			generoUsuarioComite = (generoUsuarioComite)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = generoUsuarioComite.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		generoUsuarioComiteModelImpl generoUsuarioComiteModelImpl = this;

		generoUsuarioComiteModelImpl._originalUserId = generoUsuarioComiteModelImpl._userId;

		generoUsuarioComiteModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<generoUsuarioComite> toCacheModel() {
		generoUsuarioComiteCacheModel generoUsuarioComiteCacheModel = new generoUsuarioComiteCacheModel();

		generoUsuarioComiteCacheModel.id = getId();

		generoUsuarioComiteCacheModel.Distrito = getDistrito();

		String Distrito = generoUsuarioComiteCacheModel.Distrito;

		if ((Distrito != null) && (Distrito.length() == 0)) {
			generoUsuarioComiteCacheModel.Distrito = null;
		}

		generoUsuarioComiteCacheModel.userId = getUserId();

		String userId = generoUsuarioComiteCacheModel.userId;

		if ((userId != null) && (userId.length() == 0)) {
			generoUsuarioComiteCacheModel.userId = null;
		}

		Date fecha_creacion = getFecha_creacion();

		if (fecha_creacion != null) {
			generoUsuarioComiteCacheModel.fecha_creacion = fecha_creacion.getTime();
		}
		else {
			generoUsuarioComiteCacheModel.fecha_creacion = Long.MIN_VALUE;
		}

		return generoUsuarioComiteCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", Distrito=");
		sb.append(getDistrito());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", fecha_creacion=");
		sb.append(getFecha_creacion());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.ability.genero.server.model.generoUsuarioComite");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Distrito</column-name><column-value><![CDATA[");
		sb.append(getDistrito());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fecha_creacion</column-name><column-value><![CDATA[");
		sb.append(getFecha_creacion());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = generoUsuarioComite.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			generoUsuarioComite.class
		};
	private int _id;
	private String _Distrito;
	private String _userId;
	private String _originalUserId;
	private Date _fecha_creacion;
	private long _columnBitmask;
	private generoUsuarioComite _escapedModelProxy;
}