/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model.impl;

import com.ability.genero.server.model.generoUsuario;
import com.ability.genero.server.model.generoUsuarioModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the generoUsuario service. Represents a row in the &quot;GENERO_USUARIOS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ability.genero.server.model.generoUsuarioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link generoUsuarioImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see generoUsuarioImpl
 * @see com.ability.genero.server.model.generoUsuario
 * @see com.ability.genero.server.model.generoUsuarioModel
 * @generated
 */
public class generoUsuarioModelImpl extends BaseModelImpl<generoUsuario>
	implements generoUsuarioModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a genero usuario model instance should use the {@link com.ability.genero.server.model.generoUsuario} interface instead.
	 */
	public static final String TABLE_NAME = "GENERO_USUARIOS";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "DESPACHO", Types.VARCHAR },
			{ "USER_ID", Types.VARCHAR },
			{ "FECHA_CREACION", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table GENERO_USUARIOS (ID INTEGER not null primary key,DESPACHO VARCHAR(75) null,USER_ID VARCHAR(75) null,FECHA_CREACION DATE null)";
	public static final String TABLE_SQL_DROP = "drop table GENERO_USUARIOS";
	public static final String DATA_SOURCE = "base_datos_csjDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ability.genero.server.model.generoUsuario"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ability.genero.server.model.generoUsuario"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ability.genero.server.model.generoUsuario"),
			true);
	public static long USERID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ability.genero.server.model.generoUsuario"));

	public generoUsuarioModelImpl() {
	}

	public int getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return generoUsuario.class;
	}

	public String getModelClassName() {
		return generoUsuario.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("despacho", getDespacho());
		attributes.put("userId", getUserId());
		attributes.put("fecha_creacion", getFecha_creacion());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String despacho = (String)attributes.get("despacho");

		if (despacho != null) {
			setDespacho(despacho);
		}

		String userId = (String)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date fecha_creacion = (Date)attributes.get("fecha_creacion");

		if (fecha_creacion != null) {
			setFecha_creacion(fecha_creacion);
		}
	}

	public int getId() {
		return _id;
	}

	public void setId(int id) {
		_id = id;
	}

	public String getDespacho() {
		if (_despacho == null) {
			return StringPool.BLANK;
		}
		else {
			return _despacho;
		}
	}

	public void setDespacho(String despacho) {
		_despacho = despacho;
	}

	public String getUserId() {
		if (_userId == null) {
			return StringPool.BLANK;
		}
		else {
			return _userId;
		}
	}

	public void setUserId(String userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (_originalUserId == null) {
			_originalUserId = _userId;
		}

		_userId = userId;
	}

	public String getOriginalUserId() {
		return GetterUtil.getString(_originalUserId);
	}

	public Date getFecha_creacion() {
		return _fecha_creacion;
	}

	public void setFecha_creacion(Date fecha_creacion) {
		_fecha_creacion = fecha_creacion;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public generoUsuario toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (generoUsuario)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		generoUsuarioImpl generoUsuarioImpl = new generoUsuarioImpl();

		generoUsuarioImpl.setId(getId());
		generoUsuarioImpl.setDespacho(getDespacho());
		generoUsuarioImpl.setUserId(getUserId());
		generoUsuarioImpl.setFecha_creacion(getFecha_creacion());

		generoUsuarioImpl.resetOriginalValues();

		return generoUsuarioImpl;
	}

	public int compareTo(generoUsuario generoUsuario) {
		int primaryKey = generoUsuario.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		generoUsuario generoUsuario = null;

		try {
			generoUsuario = (generoUsuario)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = generoUsuario.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		generoUsuarioModelImpl generoUsuarioModelImpl = this;

		generoUsuarioModelImpl._originalUserId = generoUsuarioModelImpl._userId;

		generoUsuarioModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<generoUsuario> toCacheModel() {
		generoUsuarioCacheModel generoUsuarioCacheModel = new generoUsuarioCacheModel();

		generoUsuarioCacheModel.id = getId();

		generoUsuarioCacheModel.despacho = getDespacho();

		String despacho = generoUsuarioCacheModel.despacho;

		if ((despacho != null) && (despacho.length() == 0)) {
			generoUsuarioCacheModel.despacho = null;
		}

		generoUsuarioCacheModel.userId = getUserId();

		String userId = generoUsuarioCacheModel.userId;

		if ((userId != null) && (userId.length() == 0)) {
			generoUsuarioCacheModel.userId = null;
		}

		Date fecha_creacion = getFecha_creacion();

		if (fecha_creacion != null) {
			generoUsuarioCacheModel.fecha_creacion = fecha_creacion.getTime();
		}
		else {
			generoUsuarioCacheModel.fecha_creacion = Long.MIN_VALUE;
		}

		return generoUsuarioCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", despacho=");
		sb.append(getDespacho());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", fecha_creacion=");
		sb.append(getFecha_creacion());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.ability.genero.server.model.generoUsuario");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>despacho</column-name><column-value><![CDATA[");
		sb.append(getDespacho());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fecha_creacion</column-name><column-value><![CDATA[");
		sb.append(getFecha_creacion());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = generoUsuario.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			generoUsuario.class
		};
	private int _id;
	private String _despacho;
	private String _userId;
	private String _originalUserId;
	private Date _fecha_creacion;
	private long _columnBitmask;
	private generoUsuario _escapedModelProxy;
}