/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model.impl;

import com.ability.genero.server.model.juresprudenciaInternacional;
import com.ability.genero.server.model.juresprudenciaInternacionalModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the juresprudenciaInternacional service. Represents a row in the &quot;GENERO_JURISPRUDENCIA_INTERNACIONAL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ability.genero.server.model.juresprudenciaInternacionalModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link juresprudenciaInternacionalImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see juresprudenciaInternacionalImpl
 * @see com.ability.genero.server.model.juresprudenciaInternacional
 * @see com.ability.genero.server.model.juresprudenciaInternacionalModel
 * @generated
 */
public class juresprudenciaInternacionalModelImpl extends BaseModelImpl<juresprudenciaInternacional>
	implements juresprudenciaInternacionalModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a juresprudencia internacional model instance should use the {@link com.ability.genero.server.model.juresprudenciaInternacional} interface instead.
	 */
	public static final String TABLE_NAME = "GENERO_JURISPRUDENCIA_INTERNACIONAL";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "REFERENCIAS", Types.VARCHAR },
			{ "ANHIO", Types.VARCHAR },
			{ "URL", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table GENERO_JURISPRUDENCIA_INTERNACIONAL (ID INTEGER not null primary key,REFERENCIAS VARCHAR(75) null,ANHIO VARCHAR(75) null,URL VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table GENERO_JURISPRUDENCIA_INTERNACIONAL";
	public static final String ORDER_BY_JPQL = " ORDER BY juresprudenciaInternacional.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GENERO_JURISPRUDENCIA_INTERNACIONAL.ID ASC";
	public static final String DATA_SOURCE = "base_datos_csjDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ability.genero.server.model.juresprudenciaInternacional"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ability.genero.server.model.juresprudenciaInternacional"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ability.genero.server.model.juresprudenciaInternacional"));

	public juresprudenciaInternacionalModelImpl() {
	}

	public int getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return juresprudenciaInternacional.class;
	}

	public String getModelClassName() {
		return juresprudenciaInternacional.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("referencias", getReferencias());
		attributes.put("anhio", getAnhio());
		attributes.put("url", getUrl());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String referencias = (String)attributes.get("referencias");

		if (referencias != null) {
			setReferencias(referencias);
		}

		String anhio = (String)attributes.get("anhio");

		if (anhio != null) {
			setAnhio(anhio);
		}

		String url = (String)attributes.get("url");

		if (url != null) {
			setUrl(url);
		}
	}

	public int getId() {
		return _id;
	}

	public void setId(int id) {
		_id = id;
	}

	public String getReferencias() {
		if (_referencias == null) {
			return StringPool.BLANK;
		}
		else {
			return _referencias;
		}
	}

	public void setReferencias(String referencias) {
		_referencias = referencias;
	}

	public String getAnhio() {
		if (_anhio == null) {
			return StringPool.BLANK;
		}
		else {
			return _anhio;
		}
	}

	public void setAnhio(String anhio) {
		_anhio = anhio;
	}

	public String getUrl() {
		if (_url == null) {
			return StringPool.BLANK;
		}
		else {
			return _url;
		}
	}

	public void setUrl(String url) {
		_url = url;
	}

	@Override
	public juresprudenciaInternacional toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (juresprudenciaInternacional)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		juresprudenciaInternacionalImpl juresprudenciaInternacionalImpl = new juresprudenciaInternacionalImpl();

		juresprudenciaInternacionalImpl.setId(getId());
		juresprudenciaInternacionalImpl.setReferencias(getReferencias());
		juresprudenciaInternacionalImpl.setAnhio(getAnhio());
		juresprudenciaInternacionalImpl.setUrl(getUrl());

		juresprudenciaInternacionalImpl.resetOriginalValues();

		return juresprudenciaInternacionalImpl;
	}

	public int compareTo(
		juresprudenciaInternacional juresprudenciaInternacional) {
		int value = 0;

		if (getId() < juresprudenciaInternacional.getId()) {
			value = -1;
		}
		else if (getId() > juresprudenciaInternacional.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		juresprudenciaInternacional juresprudenciaInternacional = null;

		try {
			juresprudenciaInternacional = (juresprudenciaInternacional)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = juresprudenciaInternacional.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<juresprudenciaInternacional> toCacheModel() {
		juresprudenciaInternacionalCacheModel juresprudenciaInternacionalCacheModel =
			new juresprudenciaInternacionalCacheModel();

		juresprudenciaInternacionalCacheModel.id = getId();

		juresprudenciaInternacionalCacheModel.referencias = getReferencias();

		String referencias = juresprudenciaInternacionalCacheModel.referencias;

		if ((referencias != null) && (referencias.length() == 0)) {
			juresprudenciaInternacionalCacheModel.referencias = null;
		}

		juresprudenciaInternacionalCacheModel.anhio = getAnhio();

		String anhio = juresprudenciaInternacionalCacheModel.anhio;

		if ((anhio != null) && (anhio.length() == 0)) {
			juresprudenciaInternacionalCacheModel.anhio = null;
		}

		juresprudenciaInternacionalCacheModel.url = getUrl();

		String url = juresprudenciaInternacionalCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			juresprudenciaInternacionalCacheModel.url = null;
		}

		return juresprudenciaInternacionalCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", referencias=");
		sb.append(getReferencias());
		sb.append(", anhio=");
		sb.append(getAnhio());
		sb.append(", url=");
		sb.append(getUrl());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.ability.genero.server.model.juresprudenciaInternacional");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>referencias</column-name><column-value><![CDATA[");
		sb.append(getReferencias());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anhio</column-name><column-value><![CDATA[");
		sb.append(getAnhio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>url</column-name><column-value><![CDATA[");
		sb.append(getUrl());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = juresprudenciaInternacional.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			juresprudenciaInternacional.class
		};
	private int _id;
	private String _referencias;
	private String _anhio;
	private String _url;
	private juresprudenciaInternacional _escapedModelProxy;
}