/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model.impl;

import com.ability.genero.server.model.juresprudenciaNacional;
import com.ability.genero.server.service.juresprudenciaNacionalLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the juresprudenciaNacional service. Represents a row in the &quot;GENERO_JURISPRUDENCIA_NACIONAL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link juresprudenciaNacionalImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see juresprudenciaNacionalImpl
 * @see com.ability.genero.server.model.juresprudenciaNacional
 * @generated
 */
public abstract class juresprudenciaNacionalBaseImpl
	extends juresprudenciaNacionalModelImpl implements juresprudenciaNacional {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a juresprudencia nacional model instance should use the {@link juresprudenciaNacional} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			juresprudenciaNacionalLocalServiceUtil.addjuresprudenciaNacional(this);
		}
		else {
			juresprudenciaNacionalLocalServiceUtil.updatejuresprudenciaNacional(this);
		}
	}
}