/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model.impl;

import com.ability.genero.server.model.juresprudenciaNacional;
import com.ability.genero.server.model.juresprudenciaNacionalModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the juresprudenciaNacional service. Represents a row in the &quot;GENERO_JURISPRUDENCIA_NACIONAL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ability.genero.server.model.juresprudenciaNacionalModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link juresprudenciaNacionalImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see juresprudenciaNacionalImpl
 * @see com.ability.genero.server.model.juresprudenciaNacional
 * @see com.ability.genero.server.model.juresprudenciaNacionalModel
 * @generated
 */
public class juresprudenciaNacionalModelImpl extends BaseModelImpl<juresprudenciaNacional>
	implements juresprudenciaNacionalModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a juresprudencia nacional model instance should use the {@link com.ability.genero.server.model.juresprudenciaNacional} interface instead.
	 */
	public static final String TABLE_NAME = "GENERO_JURISPRUDENCIA_NACIONAL";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "REFERENCIAS", Types.VARCHAR },
			{ "CORPORACION", Types.VARCHAR },
			{ "URL", Types.VARCHAR },
			{ "AMBITO", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table GENERO_JURISPRUDENCIA_NACIONAL (ID INTEGER not null primary key,REFERENCIAS VARCHAR(75) null,CORPORACION VARCHAR(75) null,URL VARCHAR(75) null,AMBITO VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table GENERO_JURISPRUDENCIA_NACIONAL";
	public static final String ORDER_BY_JPQL = " ORDER BY juresprudenciaNacional.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GENERO_JURISPRUDENCIA_NACIONAL.ID ASC";
	public static final String DATA_SOURCE = "base_datos_csjDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ability.genero.server.model.juresprudenciaNacional"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ability.genero.server.model.juresprudenciaNacional"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ability.genero.server.model.juresprudenciaNacional"));

	public juresprudenciaNacionalModelImpl() {
	}

	public int getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return juresprudenciaNacional.class;
	}

	public String getModelClassName() {
		return juresprudenciaNacional.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("referencias", getReferencias());
		attributes.put("corporacion", getCorporacion());
		attributes.put("url", getUrl());
		attributes.put("ambito", getAmbito());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String referencias = (String)attributes.get("referencias");

		if (referencias != null) {
			setReferencias(referencias);
		}

		String corporacion = (String)attributes.get("corporacion");

		if (corporacion != null) {
			setCorporacion(corporacion);
		}

		String url = (String)attributes.get("url");

		if (url != null) {
			setUrl(url);
		}

		String ambito = (String)attributes.get("ambito");

		if (ambito != null) {
			setAmbito(ambito);
		}
	}

	public int getId() {
		return _id;
	}

	public void setId(int id) {
		_id = id;
	}

	public String getReferencias() {
		if (_referencias == null) {
			return StringPool.BLANK;
		}
		else {
			return _referencias;
		}
	}

	public void setReferencias(String referencias) {
		_referencias = referencias;
	}

	public String getCorporacion() {
		if (_corporacion == null) {
			return StringPool.BLANK;
		}
		else {
			return _corporacion;
		}
	}

	public void setCorporacion(String corporacion) {
		_corporacion = corporacion;
	}

	public String getUrl() {
		if (_url == null) {
			return StringPool.BLANK;
		}
		else {
			return _url;
		}
	}

	public void setUrl(String url) {
		_url = url;
	}

	public String getAmbito() {
		if (_ambito == null) {
			return StringPool.BLANK;
		}
		else {
			return _ambito;
		}
	}

	public void setAmbito(String ambito) {
		_ambito = ambito;
	}

	@Override
	public juresprudenciaNacional toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (juresprudenciaNacional)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		juresprudenciaNacionalImpl juresprudenciaNacionalImpl = new juresprudenciaNacionalImpl();

		juresprudenciaNacionalImpl.setId(getId());
		juresprudenciaNacionalImpl.setReferencias(getReferencias());
		juresprudenciaNacionalImpl.setCorporacion(getCorporacion());
		juresprudenciaNacionalImpl.setUrl(getUrl());
		juresprudenciaNacionalImpl.setAmbito(getAmbito());

		juresprudenciaNacionalImpl.resetOriginalValues();

		return juresprudenciaNacionalImpl;
	}

	public int compareTo(juresprudenciaNacional juresprudenciaNacional) {
		int value = 0;

		if (getId() < juresprudenciaNacional.getId()) {
			value = -1;
		}
		else if (getId() > juresprudenciaNacional.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		juresprudenciaNacional juresprudenciaNacional = null;

		try {
			juresprudenciaNacional = (juresprudenciaNacional)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = juresprudenciaNacional.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<juresprudenciaNacional> toCacheModel() {
		juresprudenciaNacionalCacheModel juresprudenciaNacionalCacheModel = new juresprudenciaNacionalCacheModel();

		juresprudenciaNacionalCacheModel.id = getId();

		juresprudenciaNacionalCacheModel.referencias = getReferencias();

		String referencias = juresprudenciaNacionalCacheModel.referencias;

		if ((referencias != null) && (referencias.length() == 0)) {
			juresprudenciaNacionalCacheModel.referencias = null;
		}

		juresprudenciaNacionalCacheModel.corporacion = getCorporacion();

		String corporacion = juresprudenciaNacionalCacheModel.corporacion;

		if ((corporacion != null) && (corporacion.length() == 0)) {
			juresprudenciaNacionalCacheModel.corporacion = null;
		}

		juresprudenciaNacionalCacheModel.url = getUrl();

		String url = juresprudenciaNacionalCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			juresprudenciaNacionalCacheModel.url = null;
		}

		juresprudenciaNacionalCacheModel.ambito = getAmbito();

		String ambito = juresprudenciaNacionalCacheModel.ambito;

		if ((ambito != null) && (ambito.length() == 0)) {
			juresprudenciaNacionalCacheModel.ambito = null;
		}

		return juresprudenciaNacionalCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", referencias=");
		sb.append(getReferencias());
		sb.append(", corporacion=");
		sb.append(getCorporacion());
		sb.append(", url=");
		sb.append(getUrl());
		sb.append(", ambito=");
		sb.append(getAmbito());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.ability.genero.server.model.juresprudenciaNacional");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>referencias</column-name><column-value><![CDATA[");
		sb.append(getReferencias());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>corporacion</column-name><column-value><![CDATA[");
		sb.append(getCorporacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>url</column-name><column-value><![CDATA[");
		sb.append(getUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ambito</column-name><column-value><![CDATA[");
		sb.append(getAmbito());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = juresprudenciaNacional.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			juresprudenciaNacional.class
		};
	private int _id;
	private String _referencias;
	private String _corporacion;
	private String _url;
	private String _ambito;
	private juresprudenciaNacional _escapedModelProxy;
}