/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model.impl;

import com.ability.genero.server.model.normasNacionales;
import com.ability.genero.server.service.normasNacionalesLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the normasNacionales service. Represents a row in the &quot;GENERO_NORMAS_NACIONALES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link normasNacionalesImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see normasNacionalesImpl
 * @see com.ability.genero.server.model.normasNacionales
 * @generated
 */
public abstract class normasNacionalesBaseImpl extends normasNacionalesModelImpl
	implements normasNacionales {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a normas nacionales model instance should use the {@link normasNacionales} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			normasNacionalesLocalServiceUtil.addnormasNacionales(this);
		}
		else {
			normasNacionalesLocalServiceUtil.updatenormasNacionales(this);
		}
	}
}