/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model.impl;

import com.ability.genero.server.model.preguntasClave;
import com.ability.genero.server.model.preguntasClaveModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the preguntasClave service. Represents a row in the &quot;GENERO_PREGUNTAS_CLAVES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ability.genero.server.model.preguntasClaveModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link preguntasClaveImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see preguntasClaveImpl
 * @see com.ability.genero.server.model.preguntasClave
 * @see com.ability.genero.server.model.preguntasClaveModel
 * @generated
 */
public class preguntasClaveModelImpl extends BaseModelImpl<preguntasClave>
	implements preguntasClaveModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a preguntas clave model instance should use the {@link com.ability.genero.server.model.preguntasClave} interface instead.
	 */
	public static final String TABLE_NAME = "GENERO_PREGUNTAS_CLAVES";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.INTEGER },
			{ "PREGUNTA", Types.VARCHAR },
			{ "RESPUESTA", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table GENERO_PREGUNTAS_CLAVES (ID INTEGER not null primary key,PREGUNTA VARCHAR(75) null,RESPUESTA VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table GENERO_PREGUNTAS_CLAVES";
	public static final String ORDER_BY_JPQL = " ORDER BY preguntasClave.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GENERO_PREGUNTAS_CLAVES.ID ASC";
	public static final String DATA_SOURCE = "base_datos_csjDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ability.genero.server.model.preguntasClave"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ability.genero.server.model.preguntasClave"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ability.genero.server.model.preguntasClave"));

	public preguntasClaveModelImpl() {
	}

	public int getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return preguntasClave.class;
	}

	public String getModelClassName() {
		return preguntasClave.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("pregunta", getPregunta());
		attributes.put("respuesta", getRespuesta());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String pregunta = (String)attributes.get("pregunta");

		if (pregunta != null) {
			setPregunta(pregunta);
		}

		String respuesta = (String)attributes.get("respuesta");

		if (respuesta != null) {
			setRespuesta(respuesta);
		}
	}

	public int getId() {
		return _id;
	}

	public void setId(int id) {
		_id = id;
	}

	public String getPregunta() {
		if (_pregunta == null) {
			return StringPool.BLANK;
		}
		else {
			return _pregunta;
		}
	}

	public void setPregunta(String pregunta) {
		_pregunta = pregunta;
	}

	public String getRespuesta() {
		if (_respuesta == null) {
			return StringPool.BLANK;
		}
		else {
			return _respuesta;
		}
	}

	public void setRespuesta(String respuesta) {
		_respuesta = respuesta;
	}

	@Override
	public preguntasClave toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (preguntasClave)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		preguntasClaveImpl preguntasClaveImpl = new preguntasClaveImpl();

		preguntasClaveImpl.setId(getId());
		preguntasClaveImpl.setPregunta(getPregunta());
		preguntasClaveImpl.setRespuesta(getRespuesta());

		preguntasClaveImpl.resetOriginalValues();

		return preguntasClaveImpl;
	}

	public int compareTo(preguntasClave preguntasClave) {
		int value = 0;

		if (getId() < preguntasClave.getId()) {
			value = -1;
		}
		else if (getId() > preguntasClave.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		preguntasClave preguntasClave = null;

		try {
			preguntasClave = (preguntasClave)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = preguntasClave.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<preguntasClave> toCacheModel() {
		preguntasClaveCacheModel preguntasClaveCacheModel = new preguntasClaveCacheModel();

		preguntasClaveCacheModel.id = getId();

		preguntasClaveCacheModel.pregunta = getPregunta();

		String pregunta = preguntasClaveCacheModel.pregunta;

		if ((pregunta != null) && (pregunta.length() == 0)) {
			preguntasClaveCacheModel.pregunta = null;
		}

		preguntasClaveCacheModel.respuesta = getRespuesta();

		String respuesta = preguntasClaveCacheModel.respuesta;

		if ((respuesta != null) && (respuesta.length() == 0)) {
			preguntasClaveCacheModel.respuesta = null;
		}

		return preguntasClaveCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", pregunta=");
		sb.append(getPregunta());
		sb.append(", respuesta=");
		sb.append(getRespuesta());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.ability.genero.server.model.preguntasClave");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pregunta</column-name><column-value><![CDATA[");
		sb.append(getPregunta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>respuesta</column-name><column-value><![CDATA[");
		sb.append(getRespuesta());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = preguntasClave.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			preguntasClave.class
		};
	private int _id;
	private String _pregunta;
	private String _respuesta;
	private preguntasClave _escapedModelProxy;
}