/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ability.genero.server.model.impl;

import com.ability.genero.server.model.tipoDecision;
import com.ability.genero.server.service.tipoDecisionLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the tipoDecision service. Represents a row in the &quot;GENERO_TIPO_DECISION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tipoDecisionImpl}.
 * </p>
 *
 * @author DELL Villartech
 * @see tipoDecisionImpl
 * @see com.ability.genero.server.model.tipoDecision
 * @generated
 */
public abstract class tipoDecisionBaseImpl extends tipoDecisionModelImpl
	implements tipoDecision {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tipo decision model instance should use the {@link tipoDecision} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			tipoDecisionLocalServiceUtil.addtipoDecision(this);
		}
		else {
			tipoDecisionLocalServiceUtil.updatetipoDecision(this);
		}
	}
}